[project]
name = "mcproto-workspace"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "basedpyright==1.31.4",
    "ruff==0.13.0",
    { include-group = "test" },
    { include-group = "workspaces" },
]
test = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]
workspaces = ["mcproto", "mcdata"]

[tool.uv.sources]
mcproto = { workspace = true }
mcdata = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.basedpyright]
typeCheckingMode = "strict"
stubPath = "stubs"
disableBytesTypePromotions = false
